### ISSUE TITLE
Linux yara rules compilation problem.

### ISSUE THREAD

**Issue by MariasStory** [Neo23x0/Loki#5]
Hi Florian,

Nice tool indeed. I would like to have it linux friendly. Please, make the memory scan optional, let's say with an execution option. I disabled the memory scan and run the scanner in linux. At first, I had somewhat older version of yara and there where few compilation errors in the "yara_rules.yar". After updating yara to 3.3.0, I see "YaraSuntaxError" message in all 3 *.yar files. The error messages are quite reasonable.
I am not sure why you don't have the error messages with the combined (windows) version, as it works just fine.
Please, make the tool linux friendly and solve the problem with *.yar compilation.

PS: Giving a short update (even if you don't have a fast solution), is a good start.

Greetings,
Tolik

**Comment by Neo23x0** [comment]
v0.4 is fully compatible with Linux

Process checks are disabled by default on Linux. 
(there has always been an option --noprocs to disable them)
Yara must be installed in version 3.2+.
All yara rules are correct. There are no syntax errors.
